;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 8/7/2018 6:20:22 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$EF7E	F000			GOTO	_main
$035E	$	_Delay_1us:
;Delays.c,7 :: 			void Delay_1us() {
;Delays.c,8 :: 			Delay_us(1);
$035E	$0000	    			NOP
$0360	$0000	    			NOP
;Delays.c,9 :: 			}
$0362	$0012	    			RETURN
$0336	$	_Delay_5500us:
;Delays.c,31 :: 			void Delay_5500us() {
;Delays.c,32 :: 			Delay_us(5500);
$0336	$0E0F	    			MOVLW	15
$0338	$6E0B	    			MOVWF	STACK_11, 0
$033A	$0EFF	    			MOVLW	255
$033C	$6E0A	    			MOVWF	STACK_10, 0
$033E	$2E0B	    			DECFSZ	STACK_11, F, 0
$0340	$D001	    			BRA	$+2
$0342	$D003	    			BRA	$+4
$0344	$2E0A	    			DECFSZ	STACK_10, F, 0
$0346	$D7FE	    			BRA	$-1
$0348	$D7FA	    			BRA	$-5
$034A	$0E3E	    			MOVLW	62
$034C	$6E0A	    			MOVWF	STACK_10, 0
$034E	$2E0A	    			DECFSZ	STACK_10, F, 0
$0350	$D7FE	    			BRA	$-1
;Delays.c,33 :: 			}
$0352	$0012	    			RETURN
$0354	$	_Delay_50us:
;Delays.c,19 :: 			void Delay_50us() {
;Delays.c,20 :: 			Delay_us(50);
$0354	$0E21	    			MOVLW	33
$0356	$6E0A	    			MOVWF	STACK_10, 0
$0358	$2E0A	    			DECFSZ	STACK_10, F, 0
$035A	$D7FE	    			BRA	$-1
;Delays.c,21 :: 			}
$035C	$0012	    			RETURN
$01E2	$	_Lcd_Cmd:
$01E2	$C015	F000			MOVFF	Lcd_main_global_portaddress, STACK_0
$01E6	$C016	F001			MOVFF	Lcd_main_global_portaddress+1, STACK_0+1
$01EA	$C000	F015			MOVFF	STACK_0, Lcd_main_global_portaddress
$01EE	$C001	F016			MOVFF	STACK_0+1, Lcd_main_global_portaddress+1
$01F2	$C015	FFE9			MOVFF	lcd_main_global_portaddress+0, FSR0L
$01F6	$C016	FFEA			MOVFF	lcd_main_global_portaddress+1, FSR0H
$01FA	$5236	    			MOVF	FARG_Lcd_Cmd+0, 1, 0
$01FC	$E000	    			BZ	L_Lcd_Cmd_0
$01FE	$	L_Lcd_Cmd_0:
$01FE	$96EF	    			BCF	INDF0, ___ENABLE, 0
$0200	$94EF	    			BCF	INDF0, ___RS, 0
$0202	$9EEF	    			BCF	INDF0, ___DB7, 0
$0204	$9CEF	    			BCF	INDF0, ___DB6, 0
$0206	$9AEF	    			BCF	INDF0, ___DB5, 0
$0208	$98EF	    			BCF	INDF0, ___DB4, 0
$020A	$BE36	    			BTFSC	FARG_Lcd_Cmd+0, 7, 0
$020C	$8EEF	    			BSF	INDF0, ___DB7, 0
$020E	$BC36	    			BTFSC	FARG_Lcd_Cmd+0, 6, 0
$0210	$8CEF	    			BSF	INDF0, ___DB6, 0
$0212	$BA36	    			BTFSC	FARG_Lcd_Cmd+0, 5, 0
$0214	$8AEF	    			BSF	INDF0, ___DB5, 0
$0216	$B836	    			BTFSC	FARG_Lcd_Cmd+0, 4, 0
$0218	$88EF	    			BSF	INDF0, ___DB4, 0
$021A	$5017	    			MOVF	Lcd_cmd_status, 0, 0
$021C	$0A01	    			XORLW	1
$021E	$E103	    			BNZ	L_Lcd_Cmd_1
$0220	$94EF	    			BCF	INDF0, ___RS, 0
$0222	$EF14	F001			GOTO	L_Lcd_Cmd_2
$0226	$	L_Lcd_Cmd_1:
$0226	$84EF	    			BSF	INDF0, ___RS, 0
$0228	$	L_Lcd_Cmd_2:
$0228	$86EF	    			BSF	INDF0, ___ENABLE, 0
$022A	$ECAF	F001			CALL	_Delay_1us
$022E	$5236	    			MOVF	FARG_Lcd_Cmd+0, 1, 0
$0230	$E000	    			BZ	L_Lcd_Cmd_3
$0232	$	L_Lcd_Cmd_3:
$0232	$96EF	    			BCF	INDF0, ___ENABLE, 0
$0234	$94EF	    			BCF	INDF0, ___RS, 0
$0236	$9EEF	    			BCF	INDF0, ___DB7, 0
$0238	$9CEF	    			BCF	INDF0, ___DB6, 0
$023A	$9AEF	    			BCF	INDF0, ___DB5, 0
$023C	$98EF	    			BCF	INDF0, ___DB4, 0
$023E	$B636	    			BTFSC	FARG_Lcd_Cmd+0, 3, 0
$0240	$8EEF	    			BSF	INDF0, ___DB7, 0
$0242	$B436	    			BTFSC	FARG_Lcd_Cmd+0, 2, 0
$0244	$8CEF	    			BSF	INDF0, ___DB6, 0
$0246	$B236	    			BTFSC	FARG_Lcd_Cmd+0, 1, 0
$0248	$8AEF	    			BSF	INDF0, ___DB5, 0
$024A	$B036	    			BTFSC	FARG_Lcd_Cmd+0, 0, 0
$024C	$88EF	    			BSF	INDF0, ___DB4, 0
$024E	$5017	    			MOVF	Lcd_cmd_status, 0, 0
$0250	$0A01	    			XORLW	1
$0252	$E103	    			BNZ	L_Lcd_Cmd_4
$0254	$94EF	    			BCF	INDF0, ___RS, 0
$0256	$EF2E	F001			GOTO	L_Lcd_Cmd_5
$025A	$	L_Lcd_Cmd_4:
$025A	$84EF	    			BSF	INDF0, ___RS, 0
$025C	$	L_Lcd_Cmd_5:
$025C	$86EF	    			BSF	INDF0, ___ENABLE, 0
$025E	$ECAF	F001			CALL	_Delay_1us
$0262	$96EF	    			BCF	INDF0, ___ENABLE, 0
$0264	$5017	    			MOVF	Lcd_cmd_status, 0, 0
$0266	$0A01	    			XORLW	1
$0268	$E103	    			BNZ	L_Lcd_Cmd_6
$026A	$EC9B	F001			CALL	_Delay_5500us
$026E	$D002	    			BRA	L_Lcd_Cmd_7
$0270	$	L_Lcd_Cmd_6:
$0270	$ECAA	F001			CALL	_Delay_50us
$0274	$	L_Lcd_Cmd_7:
$0274	$0012	    			RETURN
$0008	$	_Lcd_Init:
$0008	$C030	F015			MOVFF	FARG_Lcd_Init+0, Lcd_main_global_portaddress
$000C	$C031	F016			MOVFF	FARG_Lcd_Init+1, Lcd_main_global_portaddress+1
$0010	$C015	FFE1			MOVFF	lcd_main_global_portaddress+0, FSR1L
$0014	$C016	FFE2			MOVFF	lcd_main_global_portaddress+1, FSR1H
$0018	$0E12	    			MOVLW	18
$001A	$26E1	    			ADDWF	FSR1L, F, 0
$001C	$96E7	    			BCF	INDF1, ___ENABLE, 0
$001E	$94E7	    			BCF	INDF1, ___RS, 0
$0020	$90E7	    			BCF	INDF1, ___RW, 0
$0022	$9EE7	    			BCF	INDF1, ___DB7, 0
$0024	$9CE7	    			BCF	INDF1, ___DB6, 0
$0026	$9AE7	    			BCF	INDF1, ___DB5, 0
$0028	$98E7	    			BCF	INDF1, ___DB4, 0
$002A	$0E12	    			MOVLW	18
$002C	$5EE1	    			SUBWF	FSR1L, F, 0
$002E	$96E7	    			BCF	INDF1, ___ENABLE, 0
$0030	$94E7	    			BCF	INDF1, ___RS, 0
$0032	$90E7	    			BCF	INDF1, ___RW, 0
$0034	$9EE7	    			BCF	INDF1, ___DB7, 0
$0036	$9CE7	    			BCF	INDF1, ___DB6, 0
$0038	$9AE7	    			BCF	INDF1, ___DB5, 0
$003A	$98E7	    			BCF	INDF1, ___DB4, 0
$003C	$EC9B	F001			CALL	_Delay_5500us
$0040	$8AE7	    			BSF	INDF1, ___DB5, 0
$0042	$88E7	    			BSF	INDF1, ___DB4, 0
$0044	$86E7	    			BSF	INDF1, ___ENABLE, 0
$0046	$ECAF	F001			CALL	_Delay_1us
$004A	$96E7	    			BCF	INDF1, ___ENABLE, 0
$004C	$EC9B	F001			CALL	_Delay_5500us
$0050	$8AE7	    			BSF	INDF1, ___DB5, 0
$0052	$88E7	    			BSF	INDF1, ___DB4, 0
$0054	$86E7	    			BSF	INDF1, ___ENABLE, 0
$0056	$ECAF	F001			CALL	_Delay_1us
$005A	$96E7	    			BCF	INDF1, ___ENABLE, 0
$005C	$ECAA	F001			CALL	_Delay_50us
$0060	$ECAA	F001			CALL	_Delay_50us
$0064	$8AE7	    			BSF	INDF1, ___DB5, 0
$0066	$88E7	    			BSF	INDF1, ___DB4, 0
$0068	$86E7	    			BSF	INDF1, ___ENABLE, 0
$006A	$ECAF	F001			CALL	_Delay_1us
$006E	$96E7	    			BCF	INDF1, ___ENABLE, 0
$0070	$EC9B	F001			CALL	_Delay_5500us
$0074	$8AE7	    			BSF	INDF1, ___DB5, 0
$0076	$98E7	    			BCF	INDF1, ___DB4, 0
$0078	$86E7	    			BSF	INDF1, ___ENABLE, 0
$007A	$ECAF	F001			CALL	_Delay_1us
$007E	$96E7	    			BCF	INDF1, ___ENABLE, 0
$0080	$ECAA	F001			CALL	_Delay_50us
$0084	$8AE7	    			BSF	INDF1, ___DB5, 0
$0086	$98E7	    			BCF	INDF1, ___DB4, 0
$0088	$86E7	    			BSF	INDF1, ___ENABLE, 0
$008A	$ECAF	F001			CALL	_Delay_1us
$008E	$96E7	    			BCF	INDF1, ___ENABLE, 0
$0090	$8EE7	    			BSF	INDF1, ___DB7, 0
$0092	$9CE7	    			BCF	INDF1, ___DB6, 0
$0094	$86E7	    			BSF	INDF1, ___ENABLE, 0
$0096	$ECAF	F001			CALL	_Delay_1us
$009A	$96E7	    			BCF	INDF1, ___ENABLE, 0
$009C	$ECAA	F001			CALL	_Delay_50us
$00A0	$0E00	    			MOVLW	0
$00A2	$6EE7	    			MOVWF	INDF1, 0
$00A4	$86E7	    			BSF	INDF1, ___ENABLE, 0
$00A6	$ECAF	F001			CALL	_Delay_1us
$00AA	$96E7	    			BCF	INDF1, ___ENABLE, 0
$00AC	$8EE7	    			BSF	INDF1, ___DB7, 0
$00AE	$8CE7	    			BSF	INDF1, ___DB6, 0
$00B0	$8AE7	    			BSF	INDF1, ___DB5, 0
$00B2	$88E7	    			BSF	INDF1, ___DB4, 0
$00B4	$86E7	    			BSF	INDF1, ___ENABLE, 0
$00B6	$ECAF	F001			CALL	_Delay_1us
$00BA	$96E7	    			BCF	INDF1, ___ENABLE, 0
$00BC	$ECAA	F001			CALL	_Delay_50us
$00C0	$0E00	    			MOVLW	0
$00C2	$6EE7	    			MOVWF	INDF1, 0
$00C4	$86E7	    			BSF	INDF1, ___ENABLE, 0
$00C6	$ECAF	F001			CALL	_Delay_1us
$00CA	$96E7	    			BCF	INDF1, ___ENABLE, 0
$00CC	$88E7	    			BSF	INDF1, ___DB4, 0
$00CE	$86E7	    			BSF	INDF1, ___ENABLE, 0
$00D0	$ECAF	F001			CALL	_Delay_1us
$00D4	$96E7	    			BCF	INDF1, ___ENABLE, 0
$00D6	$EC9B	F001			CALL	_Delay_5500us
$00DA	$0E00	    			MOVLW	0
$00DC	$6EE7	    			MOVWF	INDF1, 0
$00DE	$86E7	    			BSF	INDF1, ___ENABLE, 0
$00E0	$ECAF	F001			CALL	_Delay_1us
$00E4	$96E7	    			BCF	INDF1, ___ENABLE, 0
$00E6	$8CE7	    			BSF	INDF1, ___DB6, 0
$00E8	$8AE7	    			BSF	INDF1, ___DB5, 0
$00EA	$86E7	    			BSF	INDF1, ___ENABLE, 0
$00EC	$ECAF	F001			CALL	_Delay_1us
$00F0	$96E7	    			BCF	INDF1, ___ENABLE, 0
$00F2	$ECAA	F001			CALL	_Delay_50us
$00F6	$0E01	    			MOVLW	1
$00F8	$6E17	    			MOVWF	Lcd_cmd_status, 0
$00FA	$0012	    			RETURN
$0276	$	_Lcd_Out:
$0276	$D00F	    			BRA	L_Lcd_Out_17
$0278	$	L_Lcd_Out_19:
$0278	$0E80	    			MOVLW	128
$027A	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$027C	$D019	    			BRA	L_Lcd_Out_18
$027E	$	L_Lcd_Out_20:
$027E	$0EC0	    			MOVLW	192
$0280	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$0282	$D016	    			BRA	L_Lcd_Out_18
$0284	$	L_Lcd_Out_21:
$0284	$0E94	    			MOVLW	148
$0286	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$0288	$D013	    			BRA	L_Lcd_Out_18
$028A	$	L_Lcd_Out_22:
$028A	$0ED4	    			MOVLW	212
$028C	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$028E	$D010	    			BRA	L_Lcd_Out_18
$0290	$	L_Lcd_Out_23:
$0290	$0E80	    			MOVLW	128
$0292	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$0294	$D00D	    			BRA	L_Lcd_Out_18
$0296	$	L_Lcd_Out_17:
$0296	$5030	    			MOVF	FARG_Lcd_Out+0, 0, 0
$0298	$0A01	    			XORLW	1
$029A	$E0EE	    			BZ	L_Lcd_Out_19
$029C	$5030	    			MOVF	FARG_Lcd_Out+0, 0, 0
$029E	$0A02	    			XORLW	2
$02A0	$E0EE	    			BZ	L_Lcd_Out_20
$02A2	$5030	    			MOVF	FARG_Lcd_Out+0, 0, 0
$02A4	$0A03	    			XORLW	3
$02A6	$E0EE	    			BZ	L_Lcd_Out_21
$02A8	$5030	    			MOVF	FARG_Lcd_Out+0, 0, 0
$02AA	$0A04	    			XORLW	4
$02AC	$E0EE	    			BZ	L_Lcd_Out_22
$02AE	$D7F0	    			BRA	L_Lcd_Out_23
$02B0	$	L_Lcd_Out_18:
$02B0	$0431	    			DECF	FARG_Lcd_Out+1, 0, 0
$02B2	$6E00	    			MOVWF	STACK_0, 0
$02B4	$5030	    			MOVF	FARG_Lcd_Out+0, 0, 0
$02B6	$2600	    			ADDWF	STACK_0, 1, 0
$02B8	$C000	F030			MOVFF	STACK_0, FARG_Lcd_Out+0
$02BC	$C000	F036			MOVFF	STACK_0, FARG_Lcd_Cmd+0
$02C0	$ECF1	F000			CALL	_Lcd_Cmd
$02C4	$6A17	    			CLRF	Lcd_cmd_status, 0
$02C6	$6A34	    			CLRF	Lcd_Out_i_L0, 0
$02C8	$6A35	    			CLRF	Lcd_Out_i_L0+1, 0
$02CA	$	L_Lcd_Out_24:
$02CA	$5034	    			MOVF	Lcd_Out_i_L0, 0, 0
$02CC	$2432	    			ADDWF	FARG_Lcd_Out+2, 0, 0
$02CE	$6EE9	    			MOVWF	FSR0L, 0
$02D0	$5035	    			MOVF	Lcd_Out_i_L0+1, 0, 0
$02D2	$2033	    			ADDWFC	FARG_Lcd_Out+3, 0, 0
$02D4	$6EEA	    			MOVWF	FSR0L+1, 0
$02D6	$CFEE	F000			MOVFF	POSTINC0, STACK_0
$02DA	$5200	    			MOVF	STACK_0, 1, 0
$02DC	$E00D	    			BZ	L_Lcd_Out_25
$02DE	$5034	    			MOVF	Lcd_Out_i_L0, 0, 0
$02E0	$2432	    			ADDWF	FARG_Lcd_Out+2, 0, 0
$02E2	$6EE9	    			MOVWF	FSR0L, 0
$02E4	$5035	    			MOVF	Lcd_Out_i_L0+1, 0, 0
$02E6	$2033	    			ADDWFC	FARG_Lcd_Out+3, 0, 0
$02E8	$6EEA	    			MOVWF	FSR0L+1, 0
$02EA	$CFEE	F036			MOVFF	POSTINC0, FARG_Lcd_Cmd+0
$02EE	$ECF1	F000			CALL	_Lcd_Cmd
$02F2	$4A34	    			INFSNZ	Lcd_Out_i_L0, 1, 0
$02F4	$2A35	    			INCF	Lcd_Out_i_L0+1, 1, 0
$02F6	$D7E9	    			BRA	L_Lcd_Out_24
$02F8	$	L_Lcd_Out_25:
$02F8	$0E01	    			MOVLW	1
$02FA	$6E17	    			MOVWF	Lcd_cmd_status, 0
$02FC	$0012	    			RETURN
$02FE	$	GlobalInilcd4550:
$02FE	$0E48	    			MOVLW	72
$0300	$6E18	    			MOVWF	lstr1_lcd4550+0, 0
$0302	$0E45	    			MOVLW	69
$0304	$6E19	    			MOVWF	lstr1_lcd4550+1, 0
$0306	$0E4C	    			MOVLW	76
$0308	$6E1A	    			MOVWF	lstr1_lcd4550+2, 0
$030A	$0E4C	    			MOVLW	76
$030C	$6E1B	    			MOVWF	lstr1_lcd4550+3, 0
$030E	$0E4F	    			MOVLW	79
$0310	$6E1C	    			MOVWF	lstr1_lcd4550+4, 0
$0312	$0E20	    			MOVLW	32
$0314	$6E1D	    			MOVWF	lstr1_lcd4550+5, 0
$0316	$0E57	    			MOVLW	87
$0318	$6E1E	    			MOVWF	lstr1_lcd4550+6, 0
$031A	$0E4F	    			MOVLW	79
$031C	$6E1F	    			MOVWF	lstr1_lcd4550+7, 0
$031E	$0E52	    			MOVLW	82
$0320	$6E20	    			MOVWF	lstr1_lcd4550+8, 0
$0322	$0E4C	    			MOVLW	76
$0324	$6E21	    			MOVWF	lstr1_lcd4550+9, 0
$0326	$0E44	    			MOVLW	68
$0328	$6E22	    			MOVWF	lstr1_lcd4550+10, 0
$032A	$6A23	    			CLRF	lstr1_lcd4550+11, 0
$032C	$0E18	    			MOVLW	lstr1_lcd4550
$032E	$6E24	    			MOVWF	_text+0, 0
$0330	$0E00	    			MOVLW	@lstr1_lcd4550
$0332	$6E25	    			MOVWF	_text+1, 0
;lcd4550.c,5 :: 			char *text="HELLO WORLD";
$0334	$0012	    			RETURN
$00FC	$	_main:
$00FC	$EC7F	F001			CALL	GlobalInilcd4550
$0100	$0E49	    			MOVLW	73
$0102	$6E26	    			MOVWF	lstr2_lcd4550+0, 0
$0104	$0E20	    			MOVLW	32
$0106	$6E27	    			MOVWF	lstr2_lcd4550+1, 0
$0108	$0E41	    			MOVLW	65
$010A	$6E28	    			MOVWF	lstr2_lcd4550+2, 0
$010C	$0E4D	    			MOVLW	77
$010E	$6E29	    			MOVWF	lstr2_lcd4550+3, 0
$0110	$0E20	    			MOVLW	32
$0112	$6E2A	    			MOVWF	lstr2_lcd4550+4, 0
$0114	$0E46	    			MOVLW	70
$0116	$6E2B	    			MOVWF	lstr2_lcd4550+5, 0
$0118	$0E49	    			MOVLW	73
$011A	$6E2C	    			MOVWF	lstr2_lcd4550+6, 0
$011C	$0E4E	    			MOVLW	78
$011E	$6E2D	    			MOVWF	lstr2_lcd4550+7, 0
$0120	$0E45	    			MOVLW	69
$0122	$6E2E	    			MOVWF	lstr2_lcd4550+8, 0
$0124	$6A2F	    			CLRF	lstr2_lcd4550+9, 0
;lcd4550.c,6 :: 			void main()
;lcd4550.c,9 :: 			TRISB=0;
$0126	$6A93	    			CLRF	TRISB, 0
;lcd4550.c,10 :: 			for(;;)
$0128	$	L_main_0:
;lcd4550.c,17 :: 			PORTD=0;
$0128	$6A83	    			CLRF	PORTD, 0
;lcd4550.c,19 :: 			Lcd_Init(&PORTD);
$012A	$0E83	    			MOVLW	PORTD
$012C	$6E30	    			MOVWF	FARG_Lcd_Init+0, 0
$012E	$0E0F	    			MOVLW	@PORTD
$0130	$6E31	    			MOVWF	FARG_Lcd_Init+1, 0
$0132	$EC04	F000			CALL	_Lcd_Init
;lcd4550.c,20 :: 			Lcd_Cmd(LCD_CLEAR);
$0136	$0E01	    			MOVLW	1
$0138	$6E36	    			MOVWF	FARG_Lcd_Cmd+0, 0
$013A	$ECF1	F000			CALL	_Lcd_Cmd
;lcd4550.c,21 :: 			Lcd_Out(1, 4,text);
$013E	$0E01	    			MOVLW	1
$0140	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$0142	$0E04	    			MOVLW	4
$0144	$6E31	    			MOVWF	FARG_Lcd_Out+1, 0
$0146	$C024	F032			MOVFF	_text, FARG_Lcd_Out+2
$014A	$C025	F033			MOVFF	_text+1, FARG_Lcd_Out+3
$014E	$EC3B	F001			CALL	_Lcd_Out
;lcd4550.c,22 :: 			delay_ms(1000);
$0152	$0E0B	    			MOVLW	11
$0154	$6E0C	    			MOVWF	STACK_12, 0
$0156	$0EFF	    			MOVLW	255
$0158	$6E0B	    			MOVWF	STACK_11, 0
$015A	$0EFF	    			MOVLW	255
$015C	$6E0A	    			MOVWF	STACK_10, 0
$015E	$2E0C	    			DECFSZ	STACK_12, F, 0
$0160	$D001	    			BRA	$+2
$0162	$D007	    			BRA	$+8
$0164	$2E0B	    			DECFSZ	STACK_11, F, 0
$0166	$D001	    			BRA	$+2
$0168	$D003	    			BRA	$+4
$016A	$2E0A	    			DECFSZ	STACK_10, F, 0
$016C	$D7FE	    			BRA	$-1
$016E	$D7FA	    			BRA	$-5
$0170	$D7F6	    			BRA	$-9
$0172	$0E33	    			MOVLW	51
$0174	$6E0B	    			MOVWF	STACK_11, 0
$0176	$0EFF	    			MOVLW	255
$0178	$6E0A	    			MOVWF	STACK_10, 0
$017A	$2E0B	    			DECFSZ	STACK_11, F, 0
$017C	$D001	    			BRA	$+2
$017E	$D003	    			BRA	$+4
$0180	$2E0A	    			DECFSZ	STACK_10, F, 0
$0182	$D7FE	    			BRA	$-1
$0184	$D7FA	    			BRA	$-5
$0186	$0E88	    			MOVLW	136
$0188	$6E0A	    			MOVWF	STACK_10, 0
$018A	$2E0A	    			DECFSZ	STACK_10, F, 0
$018C	$D7FE	    			BRA	$-1
;lcd4550.c,23 :: 			Lcd_Out(2,1,"I AM FINE");
$018E	$0E02	    			MOVLW	2
$0190	$6E30	    			MOVWF	FARG_Lcd_Out+0, 0
$0192	$0E01	    			MOVLW	1
$0194	$6E31	    			MOVWF	FARG_Lcd_Out+1, 0
$0196	$0E26	    			MOVLW	lstr2_lcd4550
$0198	$6E32	    			MOVWF	FARG_Lcd_Out+2, 0
$019A	$0E00	    			MOVLW	@lstr2_lcd4550
$019C	$6E33	    			MOVWF	FARG_Lcd_Out+3, 0
$019E	$EC3B	F001			CALL	_Lcd_Out
;lcd4550.c,24 :: 			delay_ms(1000);
$01A2	$0E0B	    			MOVLW	11
$01A4	$6E0C	    			MOVWF	STACK_12, 0
$01A6	$0EFF	    			MOVLW	255
$01A8	$6E0B	    			MOVWF	STACK_11, 0
$01AA	$0EFF	    			MOVLW	255
$01AC	$6E0A	    			MOVWF	STACK_10, 0
$01AE	$2E0C	    			DECFSZ	STACK_12, F, 0
$01B0	$D001	    			BRA	$+2
$01B2	$D007	    			BRA	$+8
$01B4	$2E0B	    			DECFSZ	STACK_11, F, 0
$01B6	$D001	    			BRA	$+2
$01B8	$D003	    			BRA	$+4
$01BA	$2E0A	    			DECFSZ	STACK_10, F, 0
$01BC	$D7FE	    			BRA	$-1
$01BE	$D7FA	    			BRA	$-5
$01C0	$D7F6	    			BRA	$-9
$01C2	$0E33	    			MOVLW	51
$01C4	$6E0B	    			MOVWF	STACK_11, 0
$01C6	$0EFF	    			MOVLW	255
$01C8	$6E0A	    			MOVWF	STACK_10, 0
$01CA	$2E0B	    			DECFSZ	STACK_11, F, 0
$01CC	$D001	    			BRA	$+2
$01CE	$D003	    			BRA	$+4
$01D0	$2E0A	    			DECFSZ	STACK_10, F, 0
$01D2	$D7FE	    			BRA	$-1
$01D4	$D7FA	    			BRA	$-5
$01D6	$0E88	    			MOVLW	136
$01D8	$6E0A	    			MOVWF	STACK_10, 0
$01DA	$2E0A	    			DECFSZ	STACK_10, F, 0
$01DC	$D7FE	    			BRA	$-1
;lcd4550.c,26 :: 			}
$01DE	$	L_main_2:
$01DE	$D7A4	    			BRA	L_main_0
;lcd4550.c,27 :: 			}
$01E0	$D7FF	    			BRA	$
